version: '3'
services:
  myapp:
    build:
      context: ./DaprSample
      dockerfile: Dockerfile
    ports:
      - "3500:3500" # Dapr instances communicate over gRPC so we need to expose the gRPC port
    depends_on:
      - placement
    networks:
      - dapr-sidecar-network

  myapp-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "--app-id", "myapp",
      "--app-port", "5000",
      "--placement-host-address", "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--components-path", "./components"
    ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --components-path argument.
    depends_on:
      - myapp
    network_mode: "service:myapp" # Attach the nodeapp-dapr service to the nodeapp network namespace

  placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
  
networks:
  dapr-sidecar-network: